-- GENERATED by scripts/generate-projects-seed.mjs from
-- src/lib/mock/projects/roster.ts. Do not edit; run `npm run db:seed:generate`.
--
-- The 9 canonical projects. Safe to run repeatedly: a project whose id
-- already exists is left exactly as it is, so a re-run neither duplicates rows
-- nor overwrites changes made since.

insert into public.projects (
  id, name, client, domain, initials, industry, type, status, goal, market, language, target_location, summary, started_on, created_at, updated_at
)
values
  ('halcyon-fintech', 'Halcyon Fintech', 'Halcyon Financial Group', 'halcyon.example', 'HF', 'Financial services', 'saas', 'active', 'leads', 'United Kingdom', 'English (UK)', 'London, United Kingdom', 'Business banking platform competing for high-intent commercial terms against incumbent banks and comparison sites.', '2025-02-17', '2025-02-17T00:00:00Z', '2026-09-09T07:20:00Z'),
  ('verdant-home', 'Verdant Home', 'Verdant Retail Ltd', 'verdanthome.example', 'VH', 'Home and garden retail', 'ecommerce', 'needs-attention', 'ecommerce-revenue', 'United States', 'English (US)', 'United States (national)', 'Large catalogue retailer recovering from a platform migration that left indexation and internal linking damaged.', '2024-11-04', '2024-11-04T00:00:00Z', '2026-09-09T06:05:00Z'),
  ('fieldnote-media', 'Fieldnote Media', 'Fieldnote Publishing', 'fieldnote.example', 'FM', 'Digital publishing', 'publisher', 'monitoring', 'organic-traffic', 'United States', 'English (US)', 'United States (national)', 'High-volume editorial site defending informational rankings as AI answers absorb a growing share of the clicks.', '2024-06-24', '2024-06-24T00:00:00Z', '2026-09-08T16:40:00Z'),
  ('orbit-logistics', 'Orbit Logistics', 'Orbit Supply Systems', 'orbitlogistics.example', 'OL', 'Supply chain software', 'saas', 'active', 'rankings', 'Germany', 'German', 'Germany (national)', 'Freight visibility platform building topical authority in a market where the category terms are still forming.', '2025-05-12', '2025-05-12T00:00:00Z', '2026-09-09T05:35:00Z'),
  ('meridian-clinics', 'Meridian Clinics', 'Meridian Health Group', 'meridianclinics.example', 'MC', 'Healthcare', 'local', 'monitoring', 'local-visibility', 'United Kingdom', 'English (UK)', 'Manchester, United Kingdom', 'Eleven-site clinic group competing on local packs and treatment queries across the North West.', '2025-01-20', '2025-01-20T00:00:00Z', '2026-09-08T14:10:00Z'),
  ('skyline-outdoors', 'Skyline Outdoors', 'Skyline Brands', 'skylineoutdoors.example', 'SO', 'Outdoor retail', 'ecommerce', 'active', 'ecommerce-revenue', 'Canada', 'English (CA)', 'Canada (national)', 'Seasonal outdoor retailer whose category pages carry the revenue and whose peak arrives twice a year.', '2025-07-08', '2025-07-08T00:00:00Z', '2026-09-09T04:50:00Z'),
  ('northgate-legal', 'Northgate Legal', 'Northgate Partners LLP', 'northgatelegal.example', 'NL', 'Legal services', 'lead-gen', 'onboarding', 'leads', 'United Kingdom', 'English (UK)', 'Leeds, United Kingdom', 'New engagement still in discovery: baseline crawl complete, keyword set and content plan not yet signed off.', '2026-08-24', '2026-08-24T00:00:00Z', '2026-09-09T08:05:00Z'),
  ('atlas-industrial', 'Atlas Industrial', 'Atlas Manufacturing Group', 'atlasindustrial.example', 'AT', 'Industrial manufacturing', 'enterprise', 'paused', 'technical-recovery', 'United States', 'English (US)', 'United States (national)', 'Paused at the client''s request pending a replatform. Monitoring continues; no production work is scheduled.', '2024-09-30', '2024-09-30T00:00:00Z', '2026-08-21T11:25:00Z'),
  ('cobalt-ridge', 'Cobalt Ridge Realty', 'Cobalt Ridge Property', 'cobaltridge.example', 'CR', 'Property and real estate', 'lead-gen', 'needs-attention', 'ai-visibility', 'Australia', 'English (AU)', 'Sydney, Australia', 'Listings portal losing informational traffic to answer engines and needing an answer-readiness programme.', '2025-10-06', '2025-10-06T00:00:00Z', '2026-09-08T22:15:00Z')
on conflict (id) do nothing;
