-- C2 article persistence: create, save, provenance, guards and grants.
-- Part of the local PostgreSQL test harness; run only through supabase/tests/run.sh,
-- which creates and destroys its own disposable cluster. Never run against a hosted database.


\set ON_ERROR_STOP 1
create schema if not exists test_util;
grant usage on schema test_util to service_role, anon, authenticated;
create or replace function test_util.expect(p_label text, p_got jsonb, p_outcome text, p_extra text default null) returns void language plpgsql as $$
begin
  if p_got ->> 'outcome' is distinct from p_outcome or (p_extra is not null and p_got ->> 'reason' is distinct from p_extra) then
    raise exception 'FAIL %: expected % %, got %', p_label, p_outcome, coalesce(p_extra,''), p_got;
  end if;
  raise notice 'PASS %', p_label;
end $$;
create or replace function test_util.expect_error(p_label text, p_sql text, p_state text) returns void language plpgsql as $$
begin
  begin
    execute p_sql;
  exception when others then
    if sqlstate = p_state then raise notice 'PASS % (refused %)', p_label, sqlstate; return; end if;
    raise exception 'FAIL %: expected sqlstate %, got % %', p_label, p_state, sqlstate, sqlerrm;
  end;
  raise exception 'FAIL %: statement was not refused', p_label;
end $$;
grant execute on function test_util.expect(text,jsonb,text,text) to service_role, anon, authenticated;
grant execute on function test_util.expect_error(text,text,text) to service_role, anon, authenticated;

set role service_role;
-- creation
select test_util.expect('create v1', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000001',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'created');
select test_util.expect('create again is idempotent', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000001',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'exists');
select test_util.expect('unknown project', nexra_article_create('no-such-project','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'project-not-found');
select test_util.expect('plan run of another project', nexra_article_create('verdant-home','10000000-0000-4000-8000-000000000001',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'plan-run-invalid');
select test_util.expect('plan run not completed', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000004',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'plan-run-invalid');
select test_util.expect('run is not a content plan', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000005',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'plan-run-invalid');
select test_util.expect('hash mismatch', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'38e0f951654bec6dbff746878c5ef9b0ce8629ad8c3dd906b63a55addc5cbf8c','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'content-mismatch');
select test_util.expect('not canonical format', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002','{"topic":"x"}','a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'invalid-content');
select test_util.expect('broken JSON with the right prefix', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002','{"format":"nexra-article-content/1",broken','a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'invalid-content');
select test_util.expect('source hash mismatch', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"0000000000000000000000000000000000000000000000000000000000000000"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','hash-mismatch');
select test_util.expect('source row id of another version', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000002","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','version-mismatch');
select test_util.expect('source version number missing', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":9,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','not-found');
select test_util.expect('source draft of another project', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000002","version":1,"version_id":"30000000-0000-4000-8000-000000000003","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','not-found');
select test_util.expect('duplicate source', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705',('['||('[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb->0)::text||','||('[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb->0)::text||']')::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','duplicate');
select test_util.expect('no sources', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','count');
select test_util.expect('21 sources', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705',(select jsonb_agg('[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb->0) from generate_series(1,21)),'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','count');
select test_util.expect('source with a fact-check field', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705',jsonb_build_array(('[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb->0) || '{"fact_check":"passed"}'),'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','shape');
select test_util.expect('uppercase id', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-00000000000A","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','shape');
select test_util.expect('nothing written by the refusals', jsonb_build_object('outcome', (select count(*) from nexra_articles)::text), '1');

-- TS and PostgreSQL agree on bytes and hash
do $$ begin
  if (select content_sha256 from nexra_article_versions where version = 1) <> 'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705' then raise exception 'FAIL stored hash differs from TypeScript'; end if;
  if (select canonical_content from nexra_article_versions where version = 1) <> $q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$ then raise exception 'FAIL stored bytes differ'; end if;
  if (select encode(sha256(convert_to(canonical_content,'UTF8')),'hex') from nexra_article_versions where version = 1) <> 'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705' then raise exception 'FAIL PG hash differs'; end if;
  if (select source_content_sha256 from nexra_article_version_sources) <> '855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c' then raise exception 'FAIL draft hash differs'; end if;
  if (select status from nexra_articles) <> 'drafting' or (select current_version from nexra_articles) <> 1 then raise exception 'FAIL v1 state'; end if;
  raise notice 'PASS TypeScript and PostgreSQL hashes and bytes match';
end $$;
reset role;

-- approval does not carry forward; edit resets status
update nexra_articles set status = 'approved', approved_version = 1, approved_by = '00000000-0000-4000-8000-0000000000aa', approved_at = now();
set role service_role;
select test_util.expect('save v2', nexra_article_save_version('halcyon-fintech',(select id from nexra_articles where source_plan_run_id='10000000-0000-4000-8000-000000000001'),1::smallint,$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back, Edited","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'38e0f951654bec6dbff746878c5ef9b0ce8629ad8c3dd906b63a55addc5cbf8c','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":2,"version_id":"30000000-0000-4000-8000-000000000002","content_sha256":"8c60d8dc392d501408e94e8352b327e65767bb0416bc7133ea35cc84b2006d7f"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'created');
do $$ begin
  if (select status from nexra_articles) <> 'drafting' then raise exception 'FAIL status not reset'; end if;
  if (select current_version from nexra_articles) <> 2 then raise exception 'FAIL current_version'; end if;
  if (select approved_version from nexra_articles) <> 1 then raise exception 'FAIL approved_version history lost'; end if;
  if (select count(*) from nexra_article_version_sources s join nexra_article_versions v on v.id = s.article_version_id where v.version = 2) <> 1 then raise exception 'FAIL v2 sources'; end if;
  if (select canonical_content from nexra_article_versions where version = 1) <> $q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$ then raise exception 'FAIL v1 changed'; end if;
  raise notice 'PASS edit: v2 created, status drafting, approval stays on v1 as history, v1 untouched';
end $$;
select test_util.expect('stale expected version', nexra_article_save_version('halcyon-fintech',(select id from nexra_articles),1::smallint,$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'stale');
select test_util.expect('save from another project', nexra_article_save_version('verdant-home',(select id from nexra_articles),2::smallint,$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'not-found');
select test_util.expect('save with bad hash', nexra_article_save_version('halcyon-fintech',(select id from nexra_articles),2::smallint,$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'38e0f951654bec6dbff746878c5ef9b0ce8629ad8c3dd906b63a55addc5cbf8c','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'content-mismatch');
select test_util.expect('save with bad source', nexra_article_save_version('halcyon-fintech',(select id from nexra_articles),2::smallint,$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'source-invalid','count');
select test_util.expect('second article', nexra_article_create('halcyon-fintech','10000000-0000-4000-8000-000000000002',$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'a5ef8a00ec26954c1599c68a3a4b5b59bca6db95582a105db6ee5dcb647b4705','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'created');
reset role;
update nexra_articles set status = 'archived' where source_plan_run_id = '10000000-0000-4000-8000-000000000002';
set role service_role;
select test_util.expect('archived cannot be edited', nexra_article_save_version('halcyon-fintech',(select id from nexra_articles where status='archived'),1::smallint,$q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back, Edited","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$,'38e0f951654bec6dbff746878c5ef9b0ce8629ad8c3dd906b63a55addc5cbf8c','[{"draft_id":"20000000-0000-4000-8000-000000000001","version":1,"version_id":"30000000-0000-4000-8000-000000000001","content_sha256":"855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c"}]'::jsonb,'00000000-0000-4000-8000-0000000000aa'), 'archived');

-- grants: service_role reads, never writes directly
select test_util.expect_error('service_role cannot insert a version', 'insert into nexra_article_versions (article_id, version, origin, canonical_content, content_sha256, created_by) select id, 9, ''operator'', ''x'', ''x'', created_by from nexra_articles limit 1', '42501');
select test_util.expect_error('service_role cannot update a parent', 'update nexra_articles set status = ''approved''', '42501');
select test_util.expect_error('service_role cannot delete sources', 'delete from nexra_article_version_sources', '42501');
select test_util.expect_error('service_role cannot call internal helpers', 'select nexra_article_check_sources(''halcyon-fintech'', ''[]''::jsonb)', '42501');
reset role;
set role anon;
select test_util.expect_error('anon cannot read articles', 'select * from nexra_articles', '42501');
select test_util.expect_error('anon cannot read versions', 'select * from nexra_article_versions', '42501');
select test_util.expect_error('anon cannot create', 'select nexra_article_create(''a'',gen_random_uuid(),''x'',''x'',''[]''::jsonb,gen_random_uuid())', '42501');
reset role;
set role authenticated;
select test_util.expect_error('authenticated cannot read sources', 'select * from nexra_article_version_sources', '42501');
select test_util.expect_error('authenticated cannot save', 'select nexra_article_save_version(''a'',gen_random_uuid(),1::smallint,''x'',''x'',''[]''::jsonb,gen_random_uuid())', '42501');
reset role;

-- guards hold even for the table owner
select test_util.expect_error('version text cannot change', 'update nexra_article_versions set canonical_content = canonical_content', '23514');
select test_util.expect_error('version cannot be deleted', 'delete from nexra_article_versions', '23514');
select test_util.expect_error('versions cannot be truncated', 'truncate nexra_article_versions cascade', '23514');
select test_util.expect_error('source row cannot change', 'update nexra_article_version_sources set position = position', '23514');
select test_util.expect_error('source row cannot be deleted', 'delete from nexra_article_version_sources', '23514');
select test_util.expect_error('sources cannot be truncated', 'truncate nexra_article_version_sources', '23514');
select test_util.expect_error('parent project cannot change', 'update nexra_articles set project_id = ''verdant-home''', '23514');
select test_util.expect_error('parent plan run cannot change', 'update nexra_articles set source_plan_run_id = ''10000000-0000-4000-8000-000000000007''', '23514');
select test_util.expect_error('parent creator cannot change', 'update nexra_articles set created_by = gen_random_uuid()', '23514');
select test_util.expect_error('parent created_at cannot change', 'update nexra_articles set created_at = now() - interval ''1 day''', '23514');
select test_util.expect_error('current_version never moves back', 'update nexra_articles set current_version = 1 where current_version = 2', '23514');
select test_util.expect_error('article cannot be deleted', 'delete from nexra_articles', '23514');
select test_util.expect_error('articles cannot be truncated', 'truncate nexra_articles cascade', '23514');
select test_util.expect_error('stored hash must match the text', 'insert into nexra_article_versions (article_id, version, origin, canonical_content, content_sha256, created_by) select id, 9, ''operator'', $q${"format":"nexra-article-content/1","topic":"Missed-call text-back for service businesses","searchIntent":"commercial","slug":"missed-call-text-back","title":"Missed-Call Text-Back: Answering Every Lead You Could Not Pick Up","metaTitle":"Missed-Call Text-Back for Service Businesses","metaDescription":"How an automatic text reply to missed calls keeps a lead talking until someone can call back.","excerpt":"An automatic text reply to a missed call keeps the lead in the conversation.","category":"Operations","keywords":["missed call text back","missed call automation"],"lead":"A missed call is often a lead deciding where to go next.","introduction":["This article explains what a text-back does and where it stops."],"sections":[{"id":"what-it-does","heading":"What a text-back does","paragraphs":["It sends one text when a call is not answered.","The text names the business and asks how it can help."],"subsections":[{"id":"timing","heading":"Timing","paragraphs":["The reply goes out within a minute."]}]},{"id":"where-it-stops","heading":"Where it stops","paragraphs":["It does not replace calling the lead back."],"subsections":[]}],"faqs":[{"question":"Does the caller have to reply?","answer":"No. The text only opens the conversation."}],"internalLinks":[{"path":"/services#automation","anchorText":"our automation services","sectionId":"where-it-stops"}],"ctaTitle":"Stop losing missed calls","ctaBody":"Talk to us about setting up a text-back for your business.","topicDecision":"unset"}$q$, ''38e0f951654bec6dbff746878c5ef9b0ce8629ad8c3dd906b63a55addc5cbf8c'', created_by from nexra_articles limit 1', '23514');
select test_util.expect_error('source must hash to the draft text', 'insert into nexra_article_version_sources (article_version_id, position, source_draft_id, source_version, source_version_id, source_content_sha256) select id, 5, ''20000000-0000-4000-8000-000000000001'', 1, ''30000000-0000-4000-8000-000000000001'', repeat(''0'',64) from nexra_article_versions limit 1', '23514');
select test_util.expect_error('source of another project refused', 'insert into nexra_article_version_sources (article_version_id, position, source_draft_id, source_version, source_version_id, source_content_sha256) select id, 5, ''20000000-0000-4000-8000-000000000002'', 1, ''30000000-0000-4000-8000-000000000003'', ''855418bbdcb2057e9dcfd1996b4ee8acf4e2802a67431c95e3b4e882d825767c'' from nexra_article_versions limit 1', '23514');

-- no side effects on drafts, fact-checks, approvals or proposals
do $$ begin
  if exists (select 1 from nexra_content_draft_versions where fact_check is not null) then raise exception 'FAIL fact_check written'; end if;
  if exists (select 1 from nexra_content_drafts where status <> 'drafting' or approved_version is not null) then raise exception 'FAIL draft changed'; end if;
  if exists (select 1 from nexra_content_publication_proposals) then raise exception 'FAIL proposal written'; end if;
  raise notice 'PASS no draft, fact-check, approval or proposal side effects';
end $$;
