"use client";

import { useCallback, useEffect, useState } from "react";
import {
  carryArticleCheckUnit,
  freshArticleCheckUnit,
  recordArticleCheckUnit,
  type CarryArticleCheckUnitActionResult,
  type FreshArticleCheckUnitActionResult,
  type RecordArticleCheckUnitActionResult,
} from "@/app/(app)/projects/article-check-actions";
import { QueuedReview, useQueuedReview } from "@/components/agent-runs/queued-review";
import { Badge, type BadgeTone } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CARRY_BASIS_COPY, CARRY_REFUSAL_COPY, carriedLabel } from "@/lib/content/articles/checks/carry-copy";
import { offersRecordUnit } from "@/lib/content/articles/checks/eligibility";
import { MAX_UNIT_OBSERVATIONS } from "@/lib/content/articles/checks/result";
import { ARTICLE_CHECK_UNIT, articleCheckRequest } from "@/lib/crawl/review-request";
import { formatFullDate, formatTimeUtc } from "@/lib/format";
import type {
  ArticleCheckState,
  ArticleCheckUnitKind,
  ArticleCheckUnitResult,
  ArticleCheckUnitStatus,
  ArticleCheckUnitView,
  ArticleVersionChecks,
} from "@/types/content-article-check";
import type { FactCheckItem } from "@/types/content-draft";

/**
 * Article fact-check for one exact article version (Stage 5, milestone C4).
 *
 * Shows the version's check units — regenerated by the server from the
 * version's stored text, in the fixed order — each with its kind, label,
 * size, status, counts and the run it came from, and the version's check
 * state derived from those rows. For one chosen unit at a time: the shared
 * queue-and-run control for the Research & Evidence agent, and one explicit
 * click to record the run's outcome on that unit. The server re-reads the
 * article, the version, the unit and the run before anything is written,
 * and the database checks it all again.
 *
 * A fact-check only. There is no approval, proposal, publish or delete
 * control here, and no source draft's check is shown as the article's.
 */

export const ARTICLE_CHECK_NOTICE = "Article fact-check only — this does not approve or publish the article.";

type Load =
  | { readonly status: "loading" }
  | { readonly status: "ready"; readonly checks: ArticleVersionChecks }
  | { readonly status: "unavailable" }
  | { readonly status: "failed" };

const STATE_META: Readonly<Record<ArticleCheckState, { readonly label: string; readonly tone: BadgeTone }>> = {
  unchecked: { label: "Unchecked", tone: "neutral" },
  checking: { label: "Checking", tone: "accent" },
  "needs-review": { label: "Needs review", tone: "warning" },
  passed: { label: "All units passed", tone: "positive" },
};

const UNIT_META: Readonly<Record<ArticleCheckUnitStatus, { readonly label: string; readonly tone: BadgeTone }>> = {
  pending: { label: "Checking", tone: "accent" },
  passed: { label: "Passed", tone: "positive" },
  "needs-review": { label: "Needs review", tone: "warning" },
  failed: { label: "Check failed", tone: "critical" },
};

const KIND_LABEL: Readonly<Record<ArticleCheckUnitKind, string>> = {
  metadata: "Metadata",
  "lead-introduction": "Lead + intro",
  section: "Section",
  faq: "FAQ",
  cta: "CTA",
};

const FAILURE_LABEL = {
  "run-failed": "the run failed before it produced a check",
  "run-cancelled": "the run was cancelled",
  "output-malformed": "the answer was not in the check's fixed form",
  "coverage-incomplete": "the answer did not classify each numbered statement exactly once",
  "fresh-check-requested": "a fresh check was requested on a carried result",
} as const;

const REFUSAL_MESSAGE: Readonly<Record<NonNullable<ArticleVersionChecks["refusal"]>, string>> = {
  "statement-too-large": "This version cannot be checked: one statement is larger than a check unit may be.",
  "too-many-units": "This version cannot be checked: it yields more than 150 check units.",
};

async function readChecks(projectId: string, articleId: string, version: number, signal?: AbortSignal): Promise<Load> {
  const url = `/api/content-article-checks?project=${encodeURIComponent(projectId)}&article=${encodeURIComponent(articleId)}&version=${version}`;
  const response = await fetch(url, { cache: "no-store", signal });
  if (response.status === 503) return { status: "unavailable" };
  if (!response.ok) return { status: "failed" };
  const body = (await response.json()) as { checks?: ArticleVersionChecks };
  return body.checks ? { status: "ready", checks: body.checks } : { status: "failed" };
}

function stamp(iso: string): string {
  return `${formatFullDate(iso)} ${formatTimeUtc(iso)}`;
}

function countsLine(result: ArticleCheckUnitResult | null): string {
  if (result === null) return "—";
  if (result.status === "failed") return `No verdict: ${FAILURE_LABEL[result.reason]}`;
  const c = result.counts;
  return `${c.supported} supported · ${c.partial} partial · ${c.unsupported} unsupported · ${c.unverifiable} unverifiable · ${c.editorial} editorial${c.attested === undefined ? "" : ` · ${c.attested} attested`}`;
}

export function ArticleCheckSection({
  projectId,
  article,
  version,
  onArticleChanged,
}: {
  projectId: string;
  article: { readonly id: string; readonly status: string; readonly currentVersion: number };
  version: number;
  /** Called when a record moved the article's own status, so the panel re-reads it. */
  onArticleChanged: () => void;
}) {
  const [load, setLoad] = useState<Load>({ status: "loading" });
  const [selected, setSelected] = useState<number | null>(null);
  const [note, setNote] = useState<string | null>(null);

  const reload = useCallback(async () => {
    try {
      setLoad(await readChecks(projectId, article.id, version));
    } catch {
      setLoad({ status: "failed" });
    }
  }, [projectId, article.id, version]);

  useEffect(() => {
    const controller = new AbortController();
    readChecks(projectId, article.id, version, controller.signal)
      .then(setLoad)
      .catch(() => {
        if (!controller.signal.aborted) setLoad({ status: "failed" });
      });
    return () => controller.abort();
  }, [projectId, article.id, version]);

  const checks = load.status === "ready" ? load.checks : null;
  const unit = checks?.units.find((entry) => entry.index === selected) ?? null;
  const isCurrent = version === article.currentVersion;

  return (
    <section className="space-y-2 rounded border border-border p-3" aria-label="Article fact-check">
      <div className="flex flex-wrap items-center gap-2">
        <h4 className="text-[11px] font-semibold uppercase tracking-wide text-fg-subtle">Article fact-check · version {version}</h4>
        {checks !== null && (
          <Badge tone={STATE_META[checks.state].tone} dot>
            {STATE_META[checks.state].label}
          </Badge>
        )}
      </div>
      <p className="rounded border border-border bg-surface-raised px-3 py-2 text-xs text-fg-muted" role="note">
        {ARTICLE_CHECK_NOTICE}
      </p>
      <p className="text-xs text-fg-subtle">
        The version is checked in bounded units, one Research &amp; Evidence run per unit, against the records this product holds.
        Results belong to this exact version. A later version&apos;s identical unit may carry an earlier pass instead of a new run —
        only under the same checker instructions, and, when the pass rests on a record, only while the evidence is unchanged — and a
        carried result is always marked as carried.{" "}
        {isCurrent
          ? "When every unit of the current version passes, the article is marked Checked — not approved."
          : `This is an earlier version; its results are history. Only version ${article.currentVersion}'s units can mark the article Checked.`}
      </p>

      {load.status === "loading" && <p className="text-xs text-fg-subtle">Reading check units…</p>}
      {load.status === "unavailable" && <p className="text-xs text-warning">Article checks are not persisted on this deployment.</p>}
      {load.status === "failed" && (
        <div className="flex items-center gap-2 text-xs text-critical" role="status">
          <span>The check units could not be read.</span>
          <Button variant="ghost" onClick={() => void reload()}>
            Retry
          </Button>
        </div>
      )}
      {note !== null && (
        <p className="text-xs text-positive" role="status">
          {note}
        </p>
      )}

      {checks !== null && checks.refusal !== null && (
        <p className="text-xs text-warning" role="status">
          {REFUSAL_MESSAGE[checks.refusal]} Nothing is cut or skipped to make it fit; save a new version to check it.
        </p>
      )}

      {checks !== null && checks.refusal === null && (
        <>
          <p className="text-[11px] text-fg-subtle">
            {checks.counts.passed} of {checks.counts.total} units passed · {checks.counts.needsReview} need review · {checks.counts.failed} failed ·{" "}
            {checks.counts.pending} checking · {checks.counts.unchecked} unchecked
          </p>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[36rem] text-left text-xs">
              <thead className="text-[11px] uppercase tracking-wide text-fg-subtle">
                <tr>
                  <th className="py-1 pr-2 font-medium">#</th>
                  <th className="py-1 pr-2 font-medium">Unit</th>
                  <th className="py-1 pr-2 font-medium">Attested</th>
                  <th className="py-1 pr-2 font-medium">Status</th>
                  <th className="py-1 pr-2 font-medium">Result</th>
                  <th className="py-1 font-medium">
                    <span className="sr-only">Choose</span>
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {checks.units.map((entry) => (
                  <UnitRow key={entry.key} unit={entry} active={entry.index === selected} onSelect={() => setSelected(entry.index === selected ? null : entry.index)} />
                ))}
              </tbody>
            </table>
          </div>
          {unit !== null && (
            <UnitCheck
              key={`${checks.articleId}:${checks.version}:${unit.index}:${unit.sha256}`}
              projectId={projectId}
              article={article}
              checks={checks}
              unit={unit}
              onRecorded={(next, message, advanced) => {
                setLoad({ status: "ready", checks: next });
                setNote(message);
                if (advanced) onArticleChanged();
              }}
            />
          )}
        </>
      )}
    </section>
  );
}

function UnitRow({ unit, active, onSelect }: { unit: ArticleCheckUnitView; active: boolean; onSelect: () => void }) {
  const meta = unit.record === null ? null : UNIT_META[unit.record.status];
  return (
    <tr className={active ? "bg-surface-hover" : undefined}>
      <td className="py-1.5 pr-2 align-top text-fg-subtle">{unit.index}</td>
      <td className="py-1.5 pr-2 align-top">
        <span className="font-medium text-fg">{KIND_LABEL[unit.kind]}</span>
        {unit.kind === "section" && <span className="text-fg-muted"> · {unit.label}</span>}
        {unit.partCount > 1 && (
          <span className="text-fg-muted">
            {" "}
            · part {unit.part} of {unit.partCount}
          </span>
        )}
        <span className="block text-[11px] text-fg-subtle">
          {unit.key} · {unit.statementCount} statements · hash {unit.sha256.slice(0, 12)}…
        </span>
      </td>
      <td className="py-1.5 pr-2 align-top text-fg-muted" title="Statements from operator-attested paragraphs (first-hand or opinion); not checked against the records">
        {unit.attestedStatementCount === 0 ? "—" : unit.attestedStatementCount}
      </td>
      <td className="py-1.5 pr-2 align-top">
        {meta === null ? (
          <Badge tone="neutral">Unchecked</Badge>
        ) : (
          <Badge tone={meta.tone}>{meta.label}</Badge>
        )}
        {unit.record?.carriedFrom && (
          <span className="mt-0.5 block">
            <Badge tone="accent">Carried</Badge>
          </span>
        )}
      </td>
      <td className="py-1.5 pr-2 align-top text-fg-muted">
        {countsLine(unit.record?.result ?? null)}
        {unit.record !== null &&
          (unit.record.carriedFrom ? (
            <span className="block text-[11px] text-accent">{carriedLabel({ fromVersion: unit.record.carriedFrom.version, runId: unit.record.checkedByRunId })}</span>
          ) : (
            <span className="block text-[11px] text-fg-subtle">Run {unit.record.checkedByRunId}</span>
          ))}
        {unit.record === null && unit.carryOffer?.available && (
          <span className="block text-[11px] text-fg-subtle">An identical unit passed on v{unit.carryOffer.fromVersion}: it can be carried</span>
        )}
      </td>
      <td className="py-1.5 align-top text-right">
        <Button variant="ghost" onClick={onSelect} aria-pressed={active}>
          {active ? "Close" : "Open"}
        </Button>
      </td>
    </tr>
  );
}

export const CARRY_FAILURE: Readonly<Record<Exclude<CarryArticleCheckUnitActionResult, { ok: true }>["reason"], string>> = {
  unauthorized: "Your session has ended. Reload the page to sign in again.",
  "rate-limited": "Too many requests. Wait a moment and try again.",
  invalid: "This unit cannot be carried: its identifiers are not what the server expects.",
  unavailable: "Article checks are not persisted on this deployment, so nothing can be carried.",
  "not-current": "Only an unapproved article's current version can carry a result.",
  "already-recorded": "This unit already has a recorded check on this version, so nothing was carried.",
  unit: "This unit could not be resolved on the server from the stored version, so nothing was carried.",
  "not-carryable": "No earlier pass of this exact unit can be carried now.",
  "evidence-unread": "The evidence could not be re-read to compare it, so nothing was carried. Check the unit with a new run instead.",
  refused: "The database refused the carry on one of its own checks. Nothing was written.",
  failed: "The carry could not be completed. Nothing is known to have been written.",
};

const FRESH_FAILURE: Readonly<Record<Exclude<FreshArticleCheckUnitActionResult, { ok: true }>["reason"], string>> = {
  unauthorized: "Your session has ended. Reload the page to sign in again.",
  "rate-limited": "Too many requests. Wait a moment and try again.",
  invalid: "This unit cannot be cleared: its identifiers are not what the server expects.",
  unavailable: "Article checks are not persisted on this deployment.",
  "not-found": "This article was not found.",
  "version-not-found": "This version was not found.",
  refused: "The database refused: only a carried unit of an unapproved article's current version can be cleared. Nothing was written.",
  failed: "The fresh check could not be requested. Nothing is known to have been written.",
};

/** Fix F8: carry an earlier pass onto an unrecorded unit, or clear a carried one for a fresh check (confirmed first). */
function CarryControls({
  projectId,
  article,
  checks,
  unit,
  onChanged,
}: {
  projectId: string;
  article: { readonly id: string; readonly status: string; readonly currentVersion: number };
  checks: ArticleVersionChecks;
  unit: ArticleCheckUnitView;
  onChanged: (checks: ArticleVersionChecks, message: string, articleChanged: boolean) => void;
}) {
  const [busy, setBusy] = useState(false);
  const [confirming, setConfirming] = useState(false);
  const [failure, setFailure] = useState<string | null>(null);
  const editable = article.status !== "archived" && article.status !== "approved" && checks.version === article.currentVersion;
  const carried = unit.record?.carriedFrom ?? null;
  const offer = unit.record === null ? (unit.carryOffer ?? null) : null;

  async function carry() {
    if (busy) return;
    setBusy(true);
    setFailure(null);
    try {
      const result = await carryArticleCheckUnit(projectId, checks.articleId, checks.version, unit.index);
      if (result.ok) {
        onChanged(
          result.checks,
          `Unit ${unit.index}: ${carriedLabel({ fromVersion: result.record.carriedFrom?.version ?? 0, runId: result.record.checkedByRunId })}${
            result.articleStatusAdvanced ? "; every unit of the current version passed, so the article is now Checked (not approved)" : ""
          }. No run was made.`,
          result.articleStatusAdvanced,
        );
      } else {
        setFailure(result.reason === "not-carryable" ? `${CARRY_FAILURE["not-carryable"]} ${CARRY_REFUSAL_COPY[result.refusal]}` : CARRY_FAILURE[result.reason]);
      }
    } catch {
      setFailure(CARRY_FAILURE.failed);
    } finally {
      setBusy(false);
    }
  }

  async function fresh() {
    if (busy) return;
    setBusy(true);
    setFailure(null);
    try {
      const result = await freshArticleCheckUnit(projectId, checks.articleId, checks.version, unit.index, true);
      if (result.ok) {
        onChanged(
          result.checks,
          `Unit ${unit.index}: the carried result was cleared; check it with a new run${result.articleStatusReverted ? ". The article is back to Drafting until every unit passes again" : ""}.`,
          result.articleStatusReverted,
        );
      } else {
        setFailure(FRESH_FAILURE[result.reason]);
      }
    } catch {
      setFailure(FRESH_FAILURE.failed);
    } finally {
      setBusy(false);
      setConfirming(false);
    }
  }

  if (carried !== null && unit.record !== null) {
    return (
      <div className="space-y-1 rounded border border-accent/40 bg-surface-raised px-3 py-2 text-xs" role="note">
        <p className="font-medium text-fg">{carriedLabel({ fromVersion: carried.version, runId: unit.record.checkedByRunId })}</p>
        <p className="text-fg-muted">
          This result was not checked on version {checks.version}: it is version {carried.version}&apos;s pass of the identical unit (unit {carried.unitId.slice(0, 8)}), carried
          because {CARRY_BASIS_COPY[carried.basis]}, under checker instructions {carried.instructionsSha256.slice(0, 12)}…
          {carried.evidenceSha256 ? ` and evidence ${carried.evidenceSha256.slice(0, 12)}…` : ""}.
        </p>
        {editable && !confirming && (
          <Button variant="secondary" onClick={() => setConfirming(true)} disabled={busy}>
            Check again (fresh)
          </Button>
        )}
        {editable && confirming && (
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-fg-muted">
              Clear the carried result? The unit becomes unchecked-failed and needs a new paid run{article.status === "checked" ? "; the article returns to Drafting" : ""}.
            </span>
            <Button variant="primary" onClick={() => void fresh()} disabled={busy}>
              {busy ? "Clearing…" : "Clear and check fresh"}
            </Button>
            <Button variant="ghost" onClick={() => setConfirming(false)} disabled={busy}>
              Cancel
            </Button>
          </div>
        )}
        {failure && <p className="text-critical" role="status">{failure}</p>}
      </div>
    );
  }

  if (offer === null || !editable) return null;
  if (!offer.available) {
    return (
      <p className="text-xs text-fg-subtle" role="note">
        An identical unit passed on version {offer.fromVersion}, but it is not carried: {CARRY_REFUSAL_COPY[offer.reason]} Check it with a new run.
      </p>
    );
  }
  return (
    <div className="space-y-1 border-l-2 border-border pl-3 text-xs">
      <div className="flex flex-wrap items-center gap-2">
        <Button variant="secondary" icon="check" onClick={() => void carry()} disabled={busy}>
          {busy ? "Carrying…" : `Carry the v${offer.fromVersion} pass`}
        </Button>
        <span className="text-fg-subtle">
          Version {offer.fromVersion} passed this exact unit (run {offer.runId.slice(0, 8)}).{" "}
          {offer.basis === "no-supported"
            ? "It holds no SUPPORTED statement, so it rests on no record."
            : "It rests on a record: the evidence is re-read now and the carry is refused if it changed."}{" "}
          No run is made; the unit is marked as carried.
        </span>
      </div>
      {failure && <p className="text-critical" role="status">{failure}</p>}
    </div>
  );
}

export const RECORD_FAILURE: Readonly<Record<Exclude<RecordArticleCheckUnitActionResult, { ok: true }>["reason"], string>> = {
  unauthorized: "Your session has ended. Reload the page to sign in again.",
  "rate-limited": "Too many requests. Wait a moment and try again.",
  invalid: "This outcome cannot be recorded: its identifiers are not what the server expects.",
  unavailable: "Article checks are not persisted on this deployment, so nothing can be recorded.",
  "run-not-found": "This run no longer exists on the server.",
  unit: "This unit could not be resolved on the server from the stored version, so nothing was recorded.",
  ineligible: "This run is not this unit's check, or it is simulated or ungrounded, so nothing was recorded.",
  "already-recorded": "This unit already carries a final result, or a pending one from another run, so nothing was recorded.",
  refused: "The database refused the record on one of its own checks. Nothing was written.",
  failed: "The outcome could not be recorded. Nothing is known to have been written.",
};

function UnitCheck({
  projectId,
  article,
  checks,
  unit,
  onRecorded,
}: {
  projectId: string;
  article: { readonly id: string; readonly status: string; readonly currentVersion: number };
  checks: ArticleVersionChecks;
  unit: ArticleCheckUnitView;
  onRecorded: (checks: ArticleVersionChecks, message: string, advanced: boolean) => void;
}) {
  const request = articleCheckRequest(projectId, article, { version: checks.version, versionId: checks.versionId, refusal: checks.refusal }, unit);
  const check = useQueuedReview(request, `${checks.articleId}:${checks.version}:${unit.index}`, ARTICLE_CHECK_UNIT, projectId);
  const [recording, setRecording] = useState(false);
  const [recordNote, setRecordNote] = useState<string | null>(null);
  const run = check.state.status === "queued" ? check.state.run : null;
  const target = { articleId: checks.articleId, articleVersion: checks.version, articleVersionId: checks.versionId, unitIndex: unit.index };
  const recordable = run !== null && offersRecordUnit(run, target);
  const final = unit.record !== null && (unit.record.status === "passed" || unit.record.status === "needs-review");
  const alreadyThisRun = run !== null && unit.record !== null && unit.record.checkedByRunId === run.id && unit.record.status !== "pending";

  async function record() {
    if (recording || run === null || !recordable) return;
    setRecording(true);
    setRecordNote(null);
    try {
      const result = await recordArticleCheckUnit(projectId, checks.articleId, checks.version, unit.index, run.id);
      if (result.ok) {
        const status = UNIT_META[result.record.status].label.toLowerCase();
        onRecorded(
          result.checks,
          result.recorded
            ? `Unit ${unit.index} recorded as ${status}${result.articleStatusAdvanced ? "; every unit of the current version passed, so the article is now Checked (not approved)" : ""}.`
            : `Unit ${unit.index} already carried this run's outcome.`,
          result.articleStatusAdvanced,
        );
      } else {
        setRecordNote(RECORD_FAILURE[result.reason]);
      }
    } catch {
      setRecordNote(RECORD_FAILURE.failed);
    } finally {
      setRecording(false);
    }
  }

  const recordLabel =
    run === null
      ? "Record outcome"
      : run.status === "queued" || run.status === "running"
        ? "Record as checking"
        : run.status === "completed"
          ? "Record result on this unit"
          : "Record as failed";

  return (
    <div className="space-y-2 rounded border border-border p-3">
      <div className="flex flex-wrap items-center gap-2 text-xs">
        <span className="font-medium text-fg">
          Unit {unit.index} · {KIND_LABEL[unit.kind]}
          {unit.kind === "section" ? ` · ${unit.label}` : ""}
          {unit.partCount > 1 ? ` · part ${unit.part} of ${unit.partCount}` : ""}
        </span>
        <span className="text-fg-subtle">
          {unit.key} · {unit.statementCount} statements (S1–S{unit.statementCount}) · {unit.bytes} bytes · hash {unit.sha256}
        </span>
      </div>

      <CarryControls projectId={projectId} article={article} checks={checks} unit={unit} onChanged={onRecorded} />
      {unit.record !== null && unit.record.result !== null && <UnitResult result={unit.record.result} />}
      {unit.record !== null && unit.record.status === "pending" && (
        <p className="text-xs text-fg-muted">
          Checking: run {unit.record.checkedByRunId} is queued or running. Record its outcome here once it finishes.
        </p>
      )}

      {!final && article.status !== "archived" && (
        <>
          <QueuedReview review={ARTICLE_CHECK_UNIT} nested {...check} />
          {run !== null && !alreadyThisRun && (
            <div className="space-y-1 border-l-2 border-border pl-3">
              <div className="flex flex-wrap items-center gap-2">
                <Button variant="primary" icon="check" onClick={() => void record()} disabled={!recordable || recording}>
                  {recording ? "Recording…" : recordLabel}
                </Button>
                <span className="text-xs text-fg-subtle">
                  {recordable
                    ? "Writes this run's outcome onto this unit of this exact version. The article text is not changed, and nothing is approved or published."
                    : "This run is not this unit's check, so its outcome cannot be recorded here."}
                </span>
              </div>
              {recordNote && (
                <p className="text-xs text-critical" role="status">
                  {recordNote}
                </p>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}

function UnitResult({ result }: { result: ArticleCheckUnitResult }) {
  if (result.status === "failed") {
    const defect = result.coverage;
    return (
      <div className="space-y-1">
        <p className="text-xs text-critical">
          Check failed — {FAILURE_LABEL[result.reason]} (run {result.checkedByRunId}, recorded {stamp(result.recordedAt)}). This is not a verdict on the
          content; the unit can be checked again with a new run.
        </p>
        {result.carriedFrom && (
          <p className="text-xs text-fg-subtle">
            The cleared result had been {carriedLabel({ fromVersion: result.carriedFrom.version, runId: result.checkedByRunId }).toLowerCase()} ({CARRY_BASIS_COPY[result.carriedFrom.basis]}).
          </p>
        )}
        {defect && (
          <>
            <p className="text-xs text-fg-subtle">
              {[
                defect.missingStatements.length > 0 ? `missing S${defect.missingStatements.join(", S")}` : null,
                defect.duplicateStatements.length > 0 ? `placed more than once S${defect.duplicateStatements.join(", S")}` : null,
                defect.invalidLineCount > 0 ? `${defect.invalidLineCount} line${defect.invalidLineCount === 1 ? "" : "s"} naming no statement` : null,
                defect.observationCount > MAX_UNIT_OBSERVATIONS ? `${defect.observationCount} observations (at most ${MAX_UNIT_OBSERVATIONS})` : null,
              ]
                .filter((part) => part !== null)
                .join(" · ")}
            </p>
            {defect.invalidLines.length > 0 && (
              <ul className="space-y-0.5 text-xs text-fg-muted">
                {defect.invalidLines.map((line, i) => (
                  <li key={i}>“{line}”</li>
                ))}
              </ul>
            )}
          </>
        )}
      </div>
    );
  }
  const meta = UNIT_META[result.status];
  return (
    <div className="space-y-2">
      <div className="flex flex-wrap items-center gap-2 text-xs">
        <Badge tone={meta.tone} dot>
          {meta.label}
        </Badge>
        <span className="text-fg-subtle">
          Checked {stamp(result.checkedAt)} by run {result.checkedByRunId} against crawl {result.crawlId}
          {result.searchWindow ? ` and Search Console ${result.searchWindow}` : ""} · recorded {stamp(result.recordedAt)} · {result.classifiedCount} of{" "}
          {result.statementCount} numbered statements classified
          {result.coverageComplete
            ? " (each exactly once)"
            : ` (coverage incomplete${result.missingStatements.length > 0 ? `; missing S${result.missingStatements.join(", S")}` : ""}${
                result.duplicateStatements.length > 0 ? `; repeated S${result.duplicateStatements.join(", S")}` : ""
              }${result.unnumberedLines > 0 ? `; ${result.unnumberedLines} unnumbered line${result.unnumberedLines === 1 ? "" : "s"}` : ""})`}
        </span>
      </div>
      <p className="text-sm text-fg-muted">{result.summary}</p>
      <ItemGroup label="Supported" items={result.supported} />
      <ItemGroup label="Partly supported" items={result.partial} />
      <ItemGroup label="Unsupported — no record holds this" items={result.unsupported} />
      <ItemGroup label="Unverifiable from these records" items={result.unverifiable} />
      <ItemGroup label="Editorial — no factual claim" items={result.editorial} />
      {result.attested && <ItemGroup label="Attested by the operator — first-hand or opinion, not checked against the records (the note is its basis)" items={result.attested} />}
      {result.observations && result.observations.length > 0 && (
        <ItemGroup label="Observations — notes about no statement; not a classification and not evidence" items={result.observations} />
      )}
      <p className="text-xs text-fg-subtle">
        Unsupported means no record holds the statement, not that it is false. This is not an approval, and nothing was published.
      </p>
    </div>
  );
}

function ItemGroup({ label, items }: { label: string; items: readonly FactCheckItem[] }) {
  return (
    <div>
      <p className="text-xs font-medium text-fg">
        {label} ({items.length})
      </p>
      {items.length === 0 ? (
        <p className="text-xs text-fg-subtle">none</p>
      ) : (
        <ul className="list-disc space-y-0.5 pl-5 text-sm text-fg-muted">
          {items.map((item, index) => (
            <li key={`${index}-${item.text}`}>
              &ldquo;{item.text}&rdquo;
              {item.note ? ` — ${item.note}` : ""}
              {item.evidence ? <span className="text-xs text-fg-subtle"> [{item.evidence}]</span> : null}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
